openapi: 3.1.0
info:
  title: Job Submitter Account Manager API
  version: "0.1.0"
  description: >
    Creates accounts for job submitters (for now anyone can be a job submitter)
security:
  - mtls: []
servers:
  - url: https://localhost:3030/accounts
paths:
  /accounts:
    post:
      operationId: createAccount
      summary: Create a job_submitter account
      description: >
        A job_submitter creates an account from its identity that can be watched by itself or watchers.
      security: []
      responses:
        '201':
          description: account created has been created
        '409':
          description: An account for this identity already exists.
